### ISSUE TITLE
ImportError: cannot import name timezone

### ISSUE THREAD

**Issue by Lexus89** [skelsec/msldap#1]
Having installed msldap (on Ubuntu) and running kerberoast tool i get the following error. So far unable to fix even when upgrading the dateutil packages.

Traceback (most recent call last):
  File "./kerberoast.py", line 2, in <module>
    from msldap import *
  File "build/bdist.linux-x86_64/egg/msldap/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/msldap/core/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/msldap/core/msldap.py", line 6, in <module>
  File "build/bdist.linux-x86_64/egg/msldap/ldap_objects/__init__.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/msldap/ldap_objects/aduser.py", line 1, in <module>
ImportError: cannot import name timezone

After install i am also unable to find a "msldap" command such as described in the README.

**Comment by skelsec** [comment]
which version of ubuntu?
which version of python?

anyhow, check the new version of msldap, I made some fixes BUT I haven't touched anything on the timezones and it was always working.

**Comment by Lexus89** [comment]
This could be an issue on my side, i noticed locally it ran using Python 3.5.2 (Ubuntu 16.04.5 LTS) - yes not the 3.6 as stated at the requirements. While debugging i seem to get it working once on this setup. 

This is the error i get when starting kerberoast:
Traceback (most recent call last):
  File "/usr/local/bin/msldap", line 9, in <module>
    load_entry_point('msldap==0.0.2', 'console_scripts', 'msldap')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/msldap/__main__.py", line 9, in <module>
    from msldap.core.msldap import *
  File "/usr/local/lib/python3.5/dist-packages/msldap/core/__init__.py", line 1, in <module>
    from .msldap import MSLDAPUserCredential, MSLDAPTargetServer, MSLDAP
  File "/usr/local/lib/python3.5/dist-packages/msldap/core/msldap.py", line 12, in <module>
    from ..ldap_objects import *
  File "/usr/local/lib/python3.5/dist-packages/msldap/ldap_objects/__init__.py", line 8, in <module>
    from .aduser import MSADUser
  File "/usr/local/lib/python3.5/dist-packages/msldap/ldap_objects/aduser.py", line 8, in <module>
    from msldap.ldap_objects.common import MSLDAP_UAC, vn
  File "/usr/local/lib/python3.5/dist-packages/msldap/ldap_objects/common.py", line 20, in <module>
    class MSLDAP_UAC(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

Since i had it working for abit before i doubt this is a python version issue.
