### ISSUE TITLE
module 'msldap.protocol' has no attribute 'ldap_filter'

### ISSUE THREAD

**Issue by blshkv** [skelsec/msldap#13]
hello, I'm using the latest: msldap-0.2.14

```
bash$ msldap 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/msldap", line 11, in <module>
    load_entry_point('msldap==0.2.14', 'console_scripts', 'msldap')()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python3.6/site-packages/msldap/examples/msldapclient.py", line 20, in <module>
    from msldap.client import MSLDAPClient
  File "/usr/lib64/python3.6/site-packages/msldap/client.py", line 12, in <module>
    from msldap.protocol.query import escape_filter_chars, query_syntax_converter
  File "/usr/lib64/python3.6/site-packages/msldap/protocol/query.py", line 1, in <module>
    from .ldap_filter import Filter as LF
  File "/usr/lib64/python3.6/site-packages/msldap/protocol/ldap_filter/__init__.py", line 1, in <module>
    from .filter import Filter
  File "/usr/lib64/python3.6/site-packages/msldap/protocol/ldap_filter/filter.py", line 4, in <module>
    import msldap.protocol.ldap_filter.parser as parser
AttributeError: module 'msldap.protocol' has no attribute 'ldap_filter'
```

any idea what's wrong?

**Comment by blshkv** [comment]
Here is how to reproduce: Download msldap-0.2.14.tar.gz and unpack it, run the following:
```
python3 setup.py install --user

~/.local/bin/msldap 
Traceback (most recent call last):
  File "/home/blshkv/.local/bin/msldap", line 11, in <module>
    load_entry_point('msldap==0.2.14', 'console_scripts', 'msldap')()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/blshkv/.local/lib64/python3.6/site-packages/msldap-0.2.14-py3.6.egg/msldap/examples/msldapclient.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/blshkv/.local/lib64/python3.6/site-packages/msldap-0.2.14-py3.6.egg/msldap/client.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/blshkv/.local/lib64/python3.6/site-packages/msldap-0.2.14-py3.6.egg/msldap/protocol/query.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/blshkv/.local/lib64/python3.6/site-packages/msldap-0.2.14-py3.6.egg/msldap/protocol/ldap_filter/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/blshkv/.local/lib64/python3.6/site-packages/msldap-0.2.14-py3.6.egg/msldap/protocol/ldap_filter/filter.py", line 4, in <module>
AttributeError: module 'msldap.protocol' has no attribute 'ldap_filter'

```

**Comment by skelsec** [comment]
I could not reproduce this using a fresh venv + Ubuntu 1804
Will look into this a bit more, but others have tested it on Kali as well and it was working yesterday

**Comment by blshkv** [comment]
I have installed a fresh virtualenv/pelican and the error is still the same. Not sure what's going on.

**Comment by blshkv** [comment]
So I found out that the problem is with Python3.6 only
The root cause seems mutual imports:
https://stackoverflow.com/questions/1250103/attributeerror-module-object-has-no-attribute
Basically, Python3.7 can handle it.

Not sure if you want to fix the code or lift the requirement.

**Comment by skelsec** [comment]
Decided to remove Python3.6 support instead.
