### ISSUE TITLE
Issue while reading UAC flags in AD

### ISSUE THREAD

**Issue by Golbark** [skelsec/msldap#2]
It seems that for some elements where a UAC is not defined , the script just stops.
Note: it has been seen while executing kerberoast but it seems to be a msldap related issue.

<pre>
Traceback (most recent call last):
  File "c:\users\<username>\appdata\local\programs\python\python37-32\lib\runpy.py",
 line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\<username>\appdata\local\programs\python\python37-32\lib\runpy.py",
 line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python37-32\Scripts\kerberoast.exe\__main__.py", line 9, in <module>
  File "c:\users\<username>\appdata\local\programs\python\python37-32\lib\site-packages\kerberoast\kerberoast.py", line 383, in run
    writer.writerow(user.get_row(attrs))
  File "c:\users\<username>\appdata\local\programs\python\python37-32\lib\site-packages\msldap\ldap_objects\aduser.py", line 215, in get_row
    return [t.get(x) if x[:4]!='UAC_' else self.uac_to_textflag(x) for x in attrs]
  File "c:\users\<username>\appdata\local\programs\python\python37-32\lib\site-packages\msldap\ldap_objects\aduser.py", line 215, in <listcomp>
    return [t.get(x) if x[:4]!='UAC_' else self.uac_to_textflag(x) for x in attrs]
  File "c:\users\<username>\appdata\local\programs\python\python37-32\lib\site-packages\msldap\ldap_objects\aduser.py", line 209, in uac_to_textflag
    if self.userAccountControl & attr:
TypeError: unsupported operand type(s) for &: 'NoneType' and 'MSLDAP_UAC'
</pre>

**Comment by skelsec** [comment]
Please attach the integer/bytearray for the UAC that causes the error.

**Comment by Golbark** [comment]
The UAC field returned by the AD is blank (probably because of permissions issues)

**Comment by skelsec** [comment]
New version should fix this issue now, please let me know if you still have this issue
